### ISSUE TITLE
Farbwahlfeld Gruppe J

### ISSUE THREAD

**Issue by Kkneiphs** [ProfGriesbauer/Programmieren3WS20222023#1]
Wird das Feld "Choose Color" geklickt, aber keine Farbe ausgewählt, sondern das Fenster über das X geschlossen lassen sich keine weiteren Auswahlen (Painter, Player, Rules) im Framework treffen.

**Comment by Xare993** [comment]
FIXED: Auch beim Schließen ohne Auswahl treten keine Fehler mehr auf
